name: whisper-env2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
      - faster-whisper
      - ctranslate2==4.3.1
      - nvidia-cublas-cu12
      - nvidia-cudnn-cu12
      - ipykernel
      - wheel
      - setuptools==69.5.1
      - moviepy
      - Pillow
      - opencv-python