name: whisper-env2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
      - faster-whisper
      - ctranslate2==4.3.1
      - nvidia-cublas-cu12
      - nvidia-cudnn-cu12
      - ipykernel
      - wheel
      - setuptools==69.5.1
      - moviepy
      - Pillow
      - opencv-python
#需要 於  https://www.gyan.dev/ffmpeg/builds/ 下載ffmpeg 並解壓縮拿出bin資料夾內的ffmpeg.exe放到專案中